### ISSUE TITLE
New Mentoring Topic

### ISSUE THREAD

**Issue by jisantangelo** [andMYhacks/infosec_mentors_project#19]
Please crate a new Mentoring Topic: - Selling the Value of your work

**Comment by andMYhacks** [comment]
Would you be able to suggest a more concise way of describing this skill? 

Not entirely sure it fits with what we're encouraging others to teach at the moment, but I'm glad to hear out the idea further!

**Comment by jisantangelo** [comment]
Much of my experience is as a CIO (Citigroup Private Bank in the
Americas).  I often found that technical staff and their managers were not
good at conveying their ideas, the benefits and all the good work that they
are doing.  What happens is that efforts that have merit are ignored and
individuals who do a lot of groundwork are not recognized.

**Comment by andMYhacks** [comment]
Very good point!

Would "Effective Communication" be a good summary? It feels like it would cover this, and a lot of other situations where conveying ideas effectively is of paramount importance.

**Comment by jisantangelo** [comment]
Although it is a good catch all phrase, too often developers don't think
about "selling" themselves and their ideas.  They think that selling is
something to be frowned on.

**Comment by defense4153** [comment]
I second the observation on people not thinking about selling themselves and the stigma of "selling" as a term. It's very common for people who've never worked in a position where direct marketing was a core competency to have a negative reaction to the concept and it becomes a barrier to professional growth. But "Effective Communication" isn't enough to communicate the concept at first glance. Some alternatives:
Expressing Value in Your Idea
Pitching Your Project
Getting Approval for Your Solution
Building Value in Your Work

**Comment by jisantangelo** [comment]
How about

Pitching your project ..... and yourself !

**Comment by defense4153** [comment]
Nice, but a little long for the field:
Pitching Your Project and You
The Art of Pitching Your Work

Thoughts?

**Comment by jisantangelo** [comment]
Either would be fine

**Comment by andMYhacks** [comment]
Thank you @jisantangelo and @defense4153 for your thoughtful discussion on this topic. After much consideration, I felt that "selling" or "pitching" was not really the right term for what I'm hoping people will teach or share with one another on the project. Part of this is because I myself don't like the idea of "selling" or "being sold" on an idea; rather, I would prefer someone truly believe why something is the right course of action - and then be able to clearly express that belief. 

I find myself largely in agreement with what Simon Sinek talks about in his book (and Ted Talk of the same name), "Start with Why". If a person knows why something is the right thing to do, and can effectively communicate it, then following that person's lead becomes almost instinctive. I'd encourage you both to check out the Ted Talk if you haven't: ([Start with Why](https://www.youtube.com/watch?v=u4ZoJKF_VuA)). I hope you both find it as enjoyable as I have!

With that all said, I've added "Effective Communication" to the skills list in merge #20 - because I do find a lot of value in it, and it can mean a lot of things to a lot of people.
